# Shell variables
# Generated by 'wal'
wallpaper='/home/Ziggy/.wallpapers/wallpaper.jpg'

# Special
background='#292826'
foreground='#a7b4c0'
cursor='#e3e2eb'

# Colors
color0='#292826'
color1='#981d1b'
color2='#5e4a25'
color3='#996d1b'
color4='#354b57'
color5='#6a3845'
color6='#5b5061'
color7='#707880'
color8='#3b3a37'
color9='#fb1f1b'
color10='#b18635'
color11='#fcad1b'
color12='#4e84a1'
color13='#b84d69'
color14='#926fa5'
color15='#a7b4c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
