# Shell variables
# Generated by 'wal'
wallpaper='/home/Ziggy/.config/wpg/wallpapers/wallpaper.png'

# Special
background='#0c0b0a'
foreground='#fdffff'
cursor='#e6e8e7'

# Colors
color0='#0c0b0a'
color1='#71899C'
color2='#A3A3A1'
color3='#C7BBBA'
color4='#D6D6D2'
color5='#E1DDD8'
color6='#E2E1DD'
color7='#e6e8e7'
color8='#221f1c'
color9='#81b4dc'
color10='#e8e8bc'
color11='#ffded8'
color12='#ffffe3'
color13='#ffffe0'
color14='#ffffe2'
color15='#fdffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
